name: Leer archivo hola.txt
description: "Acción que lee el archivo hola.txt y lo imprime"

runs:
  using: "composite"  # Usamos una acción compuesta
  steps:
    - name: Leer el archivo hola.txt
      run: cat /github/workspace/hola.txt  # Comando correcto para leer el archivo


#Las acciones sueltas están pensadas para ser utilizadas dentro de workflows.

#Para ejecutar la acción suelta, solo necesitas ejecutar el workflow que la contiene desde la pestaña Actions de tu repositorio en GitHub.

#No puedes ejecutar una acción directamente en tu terminal; debe ser invocada desde un workflow.