name: Leer archivo hola.txt
description: "Acción que lee el archivo hola.txt y lo imprime"

runs:
  using: "docker"
  image: "ubuntu:latest"
  entrypoint: "bash -c 'cat /github/workspace/hola.txt'"


#Las acciones sueltas están pensadas para ser utilizadas dentro de workflows.

#Para ejecutar la acción suelta, solo necesitas ejecutar el workflow que la contiene desde la pestaña Actions de tu repositorio en GitHub.

#No puedes ejecutar una acción directamente en tu terminal; debe ser invocada desde un workflow.