name: Hola Mundo en Python

on:
  workflow_dispatch:  # Ejecución manual


jobs:
  decir-hola:
    runs-on: ubuntu-latest

    - name: Configura Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Muestra un mensaje
      run: |
        python -c "print('HOLA MUNDO JAVIER GARCIA')"
