name: Hola Mundo

on:
  workflow_dispatch:  # Ejecución manual

jobs:
  decir-hola:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v4  # Este paso es esencial para usar archivos de tu propio repositorio

    - name: mensaje
      run: echo javier garcia

    - name: Usar la acción de leer hola.txt
      uses: ./.github/actions/leer-hola  # Usamos la acción que creamos, importante tneer el action.yml dentro